// example/svelte/src/App.svelte
<script>
	export let name;
</script>

<main>
	<h1>Hello {name}!</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
  <nav class="bg-teal-50 text-red-200">
    Windi CSS test
  </nav>
  <div
    class="px-5 p-1 mx-auto text-5xl font-light bg-red-200 text-white transition-all hover:(text-green-100 rounded-full bg-teal-900)"
  >
    Hello World
  </div>
  <h2 class="btn">
    Button
  </h2>
  <div class="bar">
    Bar test
  </div>
  <div class="bg-black !bg-red-200 bg-blue-200">
    Without ! (red)
  </div>
  <div class="bg-black bg-blue-200 bg-red-200 text-xl2">
    With ! (blue)
  </div>
</main>

<style lang="postcss">
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
  .bar {
    @apply bg-pink-200 text-white p-4 w-1/4;
  }

  @screen md {
    .bar {
      @apply bg-pink-300;
    }
  }
</style>

// example/vue3/src/App.vue
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <nav>
    Windi test CSS
  </nav>
  <div
    class="px-5 p-1 text-red hover:(text-green-100 rounded-full bg-teal-900)"
    :class="{ 'bg-teal-100': true, 'hover:w-1/3': true }"
  >
    Hello World
  </div>
  <h2 class="btn">
    Button
  </h2>
  <div class="bar">
    Bar
  </div>
  <Foo />

  <div class="bg-black bg-blue-200 bg-red-200">
    Without ! (red)
  </div>
  <div class="bg-black !bg-blue-200 bg-red-200">
    With ! (blue)
  </div>
</template>

<script>
import './assets/test.css'

export default {
  name: 'App',
}
</script>

<style lang="postcss" scoped>
.bar {
  @apply bg-pink-400 text-white p-4 w-1/4;
}

@screen md {
  .bar {
    background: red;
  }
}
</style>
